name = "polymerpim-eager"
directory = "{benchmark_root}/polymerpim/{benchmark}"
parameter_file = "Param.h"
setup = [
  "make -C \"{repo}\" install DESTDIR=\"{install}\" PIPELINE=0 JIT=0 LOGGING=3 TRACE=0 JULIA=__skip_julia_wrapper__",
]
build = ["make clean", "make"]
run = "./run"
timing_label = "polymerpim"
use_profile = false
