# GENERATED BY tools/generate.py. DO NOT EDIT
#
# Opcode numbering for internal RPN programs, kept in step
# with common/opcodes.h by the generator.

module Opcodes

const OP_IDENTITY = UInt8(0)
const OP_NEGATE = UInt8(1)
const OP_ABS = UInt8(2)
const OP_ADD = UInt8(3)
const OP_SUB = UInt8(4)
const OP_MUL = UInt8(5)
const OP_DIV = UInt8(6)
const OP_ASR = UInt8(7)
const OP_EQ = UInt8(8)
const OP_LT = UInt8(9)
const OP_GT = UInt8(10)
const OP_GE = UInt8(11)
const OP_LE = UInt8(12)
const OP_ADD_SCALAR = UInt8(13)
const OP_SUB_SCALAR = UInt8(14)
const OP_MUL_SCALAR = UInt8(15)
const OP_DIV_SCALAR = UInt8(16)
const OP_ASR_SCALAR = UInt8(17)
const OP_EQ_SCALAR = UInt8(18)
const OP_LT_SCALAR = UInt8(19)
const OP_GT_SCALAR = UInt8(20)
const OP_GE_SCALAR = UInt8(21)
const OP_LE_SCALAR = UInt8(22)
const OP_MIN = UInt8(23)
const OP_MAX = UInt8(24)
const OP_SUM = UInt8(25)
const OP_PRODUCT = UInt8(26)
const OP_SELECT = UInt8(27)
const OP_ARGMIN_K = UInt8(28)
const OP_ARGMAX_K = UInt8(29)
const OP_PUSH_INPUT = UInt8(30)
const OP_PUSH_OPERAND_0 = UInt8(31)
const OP_PUSH_OPERAND_1 = UInt8(32)
const OP_PUSH_OPERAND_2 = UInt8(33)
const OP_PUSH_OPERAND_3 = UInt8(34)
const OP_PUSH_OPERAND_4 = UInt8(35)
const OP_PUSH_OPERAND_5 = UInt8(36)
const OP_PUSH_OPERAND_6 = UInt8(37)
const OP_PUSH_OPERAND_7 = UInt8(38)
const OP_PUSH_OPERAND_8 = UInt8(39)
const OP_PUSH_OPERAND_9 = UInt8(40)
const OP_PUSH_OPERAND_10 = UInt8(41)
const OP_PUSH_OPERAND_11 = UInt8(42)
const OP_PUSH_OPERAND_12 = UInt8(43)
const OP_PUSH_OPERAND_13 = UInt8(44)
const OP_PUSH_OPERAND_14 = UInt8(45)
const OP_PUSH_OPERAND_15 = UInt8(46)
const OP_ADD_SCALAR_VAR = UInt8(47)
const OP_SUB_SCALAR_VAR = UInt8(48)
const OP_MUL_SCALAR_VAR = UInt8(49)
const OP_DIV_SCALAR_VAR = UInt8(50)
const OP_ASR_SCALAR_VAR = UInt8(51)
const OP_EQ_SCALAR_VAR = UInt8(52)
const OP_LT_SCALAR_VAR = UInt8(53)
const OP_GT_SCALAR_VAR = UInt8(54)
const OP_GE_SCALAR_VAR = UInt8(55)
const OP_LE_SCALAR_VAR = UInt8(56)
const OP_NEXT_CHAIN = UInt8(57)
const OP_DUP = UInt8(58)
const OP_PUSH_INDEX = UInt8(59)
const OP_LOAD_INDIRECT = UInt8(60)
const OP_ADD_INDIRECT = UInt8(61)
const OP_APPLY_INDIRECT = UInt8(62)
const OP_PUSH_SCALAR = UInt8(63)
const OP_PUSH_SCALAR_VAR = UInt8(64)
const OP_PUSH_GLOBAL_INDEX = UInt8(65)
const OP_ARGMIN_REDUCE = UInt8(66)
const OP_ARGMAX_REDUCE = UInt8(67)

# Number of inline argument bytes that follow an opcode.
function inline_bytes(op::UInt8)
    if OP_ADD_SCALAR <= op <= OP_LE_SCALAR
        return 4
    elseif OP_ADD_SCALAR_VAR <= op <= OP_LE_SCALAR_VAR
        return 1
    elseif op == OP_PUSH_SCALAR
        return 4
    elseif op == OP_PUSH_SCALAR_VAR
        return 1
    elseif op == OP_LOAD_INDIRECT || op == OP_ADD_INDIRECT
        return 1
    elseif op == OP_APPLY_INDIRECT
        return 2
    elseif op == OP_ARGMIN_K || op == OP_ARGMAX_K
        return 1
    end
    return 0
end

is_reduction(op::UInt8) = OP_MIN <= op <= OP_PRODUCT || op == OP_ARGMIN_REDUCE || op == OP_ARGMAX_REDUCE

end # module Opcodes
